### ISSUE TITLE
Currently not working for macOS Big Sur

### ISSUE THREAD

**Issue by Technofied** [aydenp/DiscordAppleMusicRichPresence#2]
Hey there,

This app seems to only intermittently work on macOS Big Sur. Please see the attachment below to see the statuses - 
I would appreciate any for this to be fixed, it is an awesome application.

<img width="248" alt="Screen Shot 2020-08-20 at 5 45 37 pm" src="https://user-images.githubusercontent.com/40795318/90754841-03706900-e30d-11ea-9b35-1cdad6de7fce.png">

<img width="30" alt="Screen Shot 2020-08-20 at 5 46 40 pm" src="https://user-images.githubusercontent.com/40795318/90754946-23a02800-e30d-11ea-81de-08fbc858ffb6.png">

**Comment by StarWitch** [comment]
Currently works just fine for me on Big Sur 11.3.1.

**Comment by jordantaylor3d** [comment]
It is also working perfectly fine for me.

**Comment by Technofied** [comment]
I've reinstalled the app, it seems to have worked itself out now. I suppose big sur was fairly new!

**Comment by alicerunsonfedora** [comment]
Seems to also be working fine on macOS Monterey 12.0.1 (I'm on an M1)
