### ISSUE TITLE
Not showing when playing from Apple Music

### ISSUE THREAD

**Issue by PedroCavaleiro** [aydenp/DiscordAppleMusicRichPresence#3]
When playing music that isn't in your library, using Apple Music, it's not possible to get the current track.

**Comment by urbanvietcong** [comment]
This problem belongs to Apple, not to the app dev. Since BigSur beta both AppleScript and Automator aren't able to retrieve the current song when it isn't added to the library. I already reported this to Apple and also discussed in another issue belonging to another project. From what I know, we can only report the bug to Apple and wait for them to fix.

**Comment by JackWilli** [comment]
This seems to be fixed in macOS 11.3 😃

**Comment by unicck** [comment]
Here are a few ways to solve why Apple Music doesn't show up in iTunes on a Mac?
First, open the iTunes app with the Apple ID you used during your subscription
Second, check your iCloud music library
Third, update your iTunes app or even your device's operating system
If you want to know how to do it, you can also check out this [article](https://www.tunesolo.com/apple-music-converter/apple-music-not-showing-up-in-itunes.html), which tells you how to do it in detail.

**Comment by PedroCavaleiro** [comment]
> Here are a few ways to solve why Apple Music doesn't show up in iTunes on a Mac?
> First, open the iTunes app with the Apple ID you used during your subscription
> Second, check your iCloud music library
> Third, update your iTunes app or even your device's operating system
> If you want to know how to do it, you can also check out this [article](https://www.tunesolo.com/apple-music-converter/apple-music-not-showing-up-in-itunes.html), which tells you how to do it in detail.

Unrelated issue, the music that I have in my library never disappeared. but as @JackWilli it's fixed in macOS 11.3
